version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tiss
      - SPRING_DATASOURCE_USERNAME=tiss_user
      - SPRING_DATASOURCE_PASSWORD=tiss_password
      - STATIC_TOKEN=seu_token_super_seguro
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tiss
      POSTGRES_USER: tiss_user
      POSTGRES_PASSWORD: tiss_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
