server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

logging:
  level:
    org.springframework: INFO
    com.backendtiss: DEBUG

tiss:
  static-token: ${STATIC_TOKEN}
